name: codeathon_usecase_5
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_gen: ^5.3.1
  go_router: ^10.0.0
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen_runner:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - .env
